stages:
  - build
  - test

.ruby_template: &ruby_job
  image: ruby:3.2
  before_script:
    - gem install bundler -v 2.4.13
    - bundle

test:
  <<: *ruby_job
  stage: test
  coverage: /\(\d+.\d+\%\) covered/
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml

rubocop:
  <<: *ruby_job
  stage: test
  script:
    - bundle exec rubocop
