stages:
  - build
  - style
  - test

.ruby_matrix: &ruby_matrix
  parallel:
    matrix:
      - RUBY_VER:
          - "3.0"
          - "3.1"
          - "3.2"

.ruby_template: &ruby_job
  <<: *ruby_matrix
  image: ruby:$RUBY_VER
  before_script:
    - gem install bundler -v 2.4.22
    - bundle

test:
  <<: *ruby_job
  stage: test
  coverage: /\(\d+.\d+\%\) covered/
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml

rubocop:
  <<: *ruby_job
  stage: style
  script:
    - bundle exec rubocop

sorbet:
  <<: *ruby_job
  stage: style
  script:
    - bundle exec srb
