stages:
  - build
  - test

.ruby_template: &ruby_job
  image: ruby:2.6
  before_script:
    - bundle

test:
  <<: *ruby_job
  stage: test
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/

rubocop:
  <<: *ruby_job
  stage: test
  script:
    - bundle exec rubocop
