require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'Gemfile'
    - '**/Gemfile'
    - 'Capfile'
    - '**/Capfile'
    - 'vendor/**/*'
    - 'env/vendor/**/*'
    - 'cookbooks/**/**'
    - 'tmp/*'
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - 'spec/**/**'

FactoryBot/CreateList:
  Include:
    - spec/factories.rb
    - spec/factories/**/*.rb
    - features/support/factories/**/*.rb

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
Metrics/ClassLength:
  CountAsOne:
    - array
    - heredoc
    - method_call

Layout/LineLength:
  Max: 120

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": "[]"
    "%Q": "[]"
    "%W": "[]"
    "%i": "[]"
    "%q": "[]"
    "%r": "{}"
    "%s": "[]"
    "%w": "[]"
    "%x": "[]"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
  AllowModifiersOnSymbols: true
